// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	api.proto
	internal.proto

It has these top-level messages:
	Mutation
	OpRequest
	OpResponse
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Airdb service

type AirdbClient interface {
	Put(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error)
	Get(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error)
}

type airdbClient struct {
	cc *grpc.ClientConn
}

func NewAirdbClient(cc *grpc.ClientConn) AirdbClient {
	return &airdbClient{cc}
}

func (c *airdbClient) Put(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	out := new(OpResponse)
	err := grpc.Invoke(ctx, "/server.airdb/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airdbClient) Get(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	out := new(OpResponse)
	err := grpc.Invoke(ctx, "/server.airdb/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Airdb service

type AirdbServer interface {
	Put(context.Context, *OpRequest) (*OpResponse, error)
	Get(context.Context, *OpRequest) (*OpResponse, error)
}

func RegisterAirdbServer(s *grpc.Server, srv AirdbServer) {
	s.RegisterService(&_Airdb_serviceDesc, srv)
}

func _Airdb_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirdbServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.airdb/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirdbServer).Put(ctx, req.(*OpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Airdb_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirdbServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/server.airdb/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirdbServer).Get(ctx, req.(*OpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Airdb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.airdb",
	HandlerType: (*AirdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Airdb_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Airdb_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x92, 0xe2, 0xcb,
	0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b, 0xcc, 0x81, 0x88, 0x1b, 0xa5, 0x73, 0xb1, 0x26, 0x66, 0x16,
	0xa5, 0x24, 0x09, 0xe9, 0x71, 0x31, 0x07, 0x94, 0x96, 0x08, 0x09, 0xea, 0x41, 0x14, 0xea, 0xf9,
	0x17, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x48, 0x09, 0x21, 0x0b, 0x15, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x2a, 0x31, 0x80, 0xd4, 0xbb, 0xa7, 0x12, 0xaf, 0x3e, 0x89, 0x0d, 0x6c, 0x9f, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x94, 0x56, 0x89, 0x33, 0x94, 0x00, 0x00, 0x00,
}
