// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	internal.proto

It has these top-level messages:
	OpRequest
	OpResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type OpRequest struct {
	Table   string `protobuf:"bytes,1,opt,name=table" json:"table,omitempty"`
	ReqBody []byte `protobuf:"bytes,3,opt,name=reqBody,proto3" json:"reqBody,omitempty"`
}

func (m *OpRequest) Reset()                    { *m = OpRequest{} }
func (m *OpRequest) String() string            { return proto1.CompactTextString(m) }
func (*OpRequest) ProtoMessage()               {}
func (*OpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OpRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *OpRequest) GetReqBody() []byte {
	if m != nil {
		return m.ReqBody
	}
	return nil
}

type OpResponse struct {
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *OpResponse) Reset()                    { *m = OpResponse{} }
func (m *OpResponse) String() string            { return proto1.CompactTextString(m) }
func (*OpResponse) ProtoMessage()               {}
func (*OpResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *OpResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto1.RegisterType((*OpRequest)(nil), "proto.OpRequest")
	proto1.RegisterType((*OpResponse)(nil), "proto.OpResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Airdb service

type AirdbClient interface {
	Put(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error)
	Get(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error)
}

type airdbClient struct {
	cc *grpc.ClientConn
}

func NewAirdbClient(cc *grpc.ClientConn) AirdbClient {
	return &airdbClient{cc}
}

func (c *airdbClient) Put(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	out := new(OpResponse)
	err := grpc.Invoke(ctx, "/proto.airdb/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *airdbClient) Get(ctx context.Context, in *OpRequest, opts ...grpc.CallOption) (*OpResponse, error) {
	out := new(OpResponse)
	err := grpc.Invoke(ctx, "/proto.airdb/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Airdb service

type AirdbServer interface {
	Put(context.Context, *OpRequest) (*OpResponse, error)
	Get(context.Context, *OpRequest) (*OpResponse, error)
}

func RegisterAirdbServer(s *grpc.Server, srv AirdbServer) {
	s.RegisterService(&_Airdb_serviceDesc, srv)
}

func _Airdb_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirdbServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.airdb/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirdbServer).Put(ctx, req.(*OpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Airdb_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirdbServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.airdb/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirdbServer).Get(ctx, req.(*OpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Airdb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.airdb",
	HandlerType: (*AirdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Airdb_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Airdb_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal.proto",
}

func init() { proto1.RegisterFile("internal.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xd6,
	0x5c, 0x9c, 0xfe, 0x05, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22, 0x5c, 0xac, 0x25,
	0x89, 0x49, 0x39, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x04, 0x17,
	0x7b, 0x51, 0x6a, 0xa1, 0x53, 0x7e, 0x4a, 0xa5, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x8c,
	0xab, 0xa4, 0xc4, 0xc5, 0x05, 0xd2, 0x5c, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x0a, 0xd2, 0x5d, 0x96,
	0x98, 0x53, 0x0a, 0xd1, 0xcd, 0x13, 0x04, 0xe1, 0x18, 0xc5, 0x73, 0xb1, 0x26, 0x66, 0x16, 0xa5,
	0x24, 0x09, 0x69, 0x71, 0x31, 0x07, 0x94, 0x96, 0x08, 0x09, 0x40, 0xec, 0xd7, 0x83, 0xdb, 0x2a,
	0x25, 0x88, 0x24, 0x02, 0x35, 0x4a, 0x8b, 0x8b, 0xd9, 0x3d, 0x95, 0x38, 0xb5, 0x4e, 0xec, 0x51,
	0x10, 0xaf, 0x24, 0xb1, 0x81, 0x29, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x8c, 0x13,
	0x50, 0xea, 0x00, 0x00, 0x00,
}
